spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

server:
  forward-headers-strategy: framework
